import { and, eq } from 'drizzle-orm';
import { randomUUID } from 'node:crypto';
import { ApiError } from '../../common/errors/api-error.js';
import type { DatabaseClient } from '../../database/client.js';
import { mapDatabaseError } from '../../database/errors.js';
import {
  announcements,
  communicationDeliveries,
  communicationMessages,
  communicationTemplates,
  enrollments,
  notificationPreferences,
  sisNotifications,
} from '../../database/schema.js';
import { SisService } from './sis.service.js';

type JsonRecord = Record<string, unknown>;
type Tenant = { organizationId: string; workspaceId: string };
type Actor = { userId?: string; role?: string; staffId?: string } | undefined;
type Recipient = { id: string; organizationId: string; kind: string; displayName: string; email?: string; phone?: string; userId?: string; studentId?: string; guardianId?: string; staffId?: string };

const managerRoles = new Set(['Owner', 'Admin']);
const allowedVars = new Set(['student_name', 'guardian_name', 'class_name', 'section_name', 'exam_name', 'due_date', 'amount', 'school_name', 'staff_name']);
function uuid() { return randomUUID(); }
function now() { return new Date().toISOString(); }
function assertText(v: unknown, label: string) { const out = String(v ?? '').trim(); if (!out) throw new ApiError(400, 'VALIDATION_FAILED', `${label} is required.`); return out; }
function payloadOf(value: unknown): JsonRecord { if (typeof value === 'string') { try { return JSON.parse(value) as JsonRecord; } catch { return {}; } } return value && typeof value === 'object' ? value as JsonRecord : {}; }
function clean<T extends JsonRecord>(value: T): T { return Object.fromEntries(Object.entries(value).filter(([, v]) => v !== undefined)) as T; }
function dbError(error: unknown): never { const mapped = mapDatabaseError(error); if (mapped.code === 'DATABASE_UNIQUE_CONSTRAINT') throw new ApiError(409, 'DATABASE_UNIQUE_CONSTRAINT', 'A communication record with the same unique scope already exists.'); throw error; }
function assertPermission(actor: Actor, permission: string): void { const role = String(actor?.role ?? 'Owner'); if (managerRoles.has(role)) return; if (role === 'Teacher' && ['communication.view', 'communication.send', 'announcement.view', 'notification.view', 'template.view', 'delivery_history.view'].includes(permission)) return; throw new ApiError(403, 'FORBIDDEN', `Unauthorized: missing permission ${permission}`); }
function dto<T extends JsonRecord>(tenant: Tenant, row: { payload: JsonRecord }): T { return { ...payloadOf(row.payload), organizationId: tenant.organizationId } as unknown as T; }
function studentName(s: JsonRecord) { return `${String(s.firstName ?? '')} ${String(s.lastName ?? '')}`.trim(); }
function guardianName(g: JsonRecord) { return `${String(g.firstName ?? '')} ${String(g.lastName ?? '')}`.trim(); }
function staffName(s: JsonRecord) { return `${String(s.firstName ?? '')} ${String(s.lastName ?? '')}`.trim(); }

export class SisCommunicationService {
  constructor(private readonly database: DatabaseClient) {}

  async resolveAudience(tenant: Tenant, audience: JsonRecord, actor?: Actor): Promise<Recipient[]> {
    const sis = new SisService(this.database);
    const [studentRows, staffRows] = await Promise.all([sis.listStudents(tenant), sis.listStaff(tenant)]);
    const activeStudents = studentRows.filter((s) => s.status === 'active') as JsonRecord[];
    const activeStaff = staffRows.filter((s) => s.status === 'active') as JsonRecord[];
    let selectedStudents: JsonRecord[] = [];
    let selectedStaff: JsonRecord[] = [];
    const recipients: Recipient[] = [];
    const type = String(audience.type ?? '');
    if (type === 'organization') { selectedStudents = activeStudents; selectedStaff = activeStaff; }
    else if (type === 'all_students' || type === 'all_guardians') selectedStudents = activeStudents;
    else if (type === 'all_staff') selectedStaff = activeStaff;
    else if (type === 'all_teachers') selectedStaff = activeStaff.filter((s) => s.staffType === 'teacher');
    else if (type === 'class' || type === 'section') {
      if (!audience.academicYear || !audience.gradeId) throw new ApiError(400, 'VALIDATION_FAILED', 'Class audience requires academic year and class.');
      if (type === 'section' && !audience.sectionId) throw new ApiError(400, 'VALIDATION_FAILED', 'Section audience requires a section.');
      const enrollmentRows = await this.database.db.select().from(enrollments).where(and(eq(enrollments.workspaceId, tenant.workspaceId), eq(enrollments.academicYear, String(audience.academicYear)), eq(enrollments.gradeId, String(audience.gradeId)), eq(enrollments.status, 'active')));
      const scoped = audience.sectionId ? enrollmentRows.filter((e) => e.sectionId === String(audience.sectionId)) : enrollmentRows;
      selectedStudents = activeStudents.filter((s) => scoped.some((e) => e.studentId === s.id));
      if (actor?.role === 'Teacher' && actor.staffId) {
        const assignments = await sis.listTeachingAssignments(tenant, { staffId: actor.staffId, academicYear: String(audience.academicYear), gradeId: String(audience.gradeId), sectionId: audience.sectionId ? String(audience.sectionId) : undefined });
        if (!assignments.some((a) => a.isActive)) throw new ApiError(403, 'FORBIDDEN', 'Teacher is not authorized for this academic communication scope.');
      }
    } else if (type === 'selected_students') selectedStudents = activeStudents.filter((s) => (audience.studentIds as unknown[] | undefined)?.map(String).includes(String(s.id)));
    else if (type === 'selected_guardians') selectedStudents = activeStudents.filter((s) => (s.guardians as JsonRecord[] | undefined)?.some((g) => (audience.guardianIds as unknown[] | undefined)?.map(String).includes(String(g.id))));
    else if (type === 'selected_staff') selectedStaff = activeStaff.filter((s) => (audience.staffIds as unknown[] | undefined)?.map(String).includes(String(s.id)));
    else if (type === 'selected_users') {
      recipients.push(...(audience.userIds as unknown[] | undefined ?? []).map((id) => ({ id: String(id), organizationId: tenant.organizationId, kind: 'user', displayName: String(id), userId: String(id) })));
    }
    if (['organization', 'all_students', 'class', 'section', 'selected_students'].includes(type)) recipients.push(...selectedStudents.map((s) => ({ id: String(s.id), organizationId: tenant.organizationId, kind: 'student', displayName: studentName(s), email: s.email as string | undefined, phone: s.phone as string | undefined, studentId: String(s.id) })));
    if (['organization', 'all_guardians', 'class', 'section', 'selected_guardians'].includes(type)) for (const s of selectedStudents) for (const g of (s.guardians as JsonRecord[] | undefined) ?? []) { if (type === 'selected_guardians' && !(audience.guardianIds as unknown[] | undefined)?.map(String).includes(String(g.id))) continue; recipients.push({ id: String(g.id), organizationId: tenant.organizationId, kind: 'guardian', displayName: guardianName(g), email: g.email as string | undefined, phone: g.phone as string | undefined, studentId: String(s.id), guardianId: String(g.id), userId: g.userId as string | undefined }); }
    recipients.push(...selectedStaff.map((s) => ({ id: String(s.id), organizationId: tenant.organizationId, kind: s.staffType === 'teacher' ? 'teacher' : 'staff', displayName: staffName(s), email: s.email as string | undefined, phone: s.phone as string | undefined, userId: s.userId as string | undefined, staffId: String(s.id) })));
    const seen = new Set<string>();
    return recipients.filter((r) => { const k = `${r.kind}:${r.id}`; if (seen.has(k)) return false; seen.add(k); return true; });
  }

  renderTemplate(template: JsonRecord, variables: Record<string, string>) {
    const supported = new Set((template.supportedVariables as string[] | undefined) ?? []);
    const render = (value: unknown) => String(value ?? '').replace(/\{\{\s*([a-zA-Z0-9_]+)\s*\}\}/g, (_, key: string) => { if (!allowedVars.has(key) || !supported.has(key)) throw new ApiError(400, 'VALIDATION_FAILED', `Unsupported template variable: ${key}`); return variables[key] || ''; });
    return { subject: render(template.subject), content: render(template.content) };
  }

  async createTemplate(tenant: Tenant, data: JsonRecord, actor?: Actor) { assertPermission(actor, 'template.manage'); assertText(data.name, 'Template name'); for (const variable of (data.supportedVariables as string[] | undefined) ?? []) if (!allowedVars.has(variable)) throw new ApiError(400, 'VALIDATION_FAILED', `Unsupported template variable: ${variable}`); const record = this.withTenant<JsonRecord>(tenant, { ...data, id: uuid(), createdAt: now(), updatedAt: now() }); await this.database.db.insert(communicationTemplates).values({ id: String(record.id), workspaceId: tenant.workspaceId, name: String(record.name), category: String(record.category ?? 'general'), status: String(record.status ?? 'active'), payload: record }).catch(dbError); return record; }
  async updateTemplate(tenant: Tenant, id: string, data: JsonRecord, actor?: Actor) { assertPermission(actor, 'template.manage'); const current = await this.getPayload(tenant, communicationTemplates, communicationTemplates.id, id, 'Template'); const record = this.withTenant<JsonRecord>(tenant, { ...current, ...data, id, updatedAt: now() }); await this.database.db.update(communicationTemplates).set({ name: String(record.name), category: String(record.category ?? 'general'), status: String(record.status ?? 'active'), payload: record, updatedAt: new Date() }).where(and(eq(communicationTemplates.workspaceId, tenant.workspaceId), eq(communicationTemplates.id, id))).catch(dbError); return record; }
  async listTemplates(tenant: Tenant) { assertPermission(undefined, 'template.view'); return (await this.database.db.select().from(communicationTemplates).where(eq(communicationTemplates.workspaceId, tenant.workspaceId))).map((r) => dto(tenant, r)); }

  async createAnnouncement(tenant: Tenant, data: JsonRecord, actor?: Actor) { assertPermission(actor, 'announcement.create'); assertText(data.title, 'Announcement title'); assertText(data.content, 'Announcement content'); const recipients = await this.resolveAudience(tenant, data.audience as JsonRecord, actor); const record = this.withTenant<JsonRecord>(tenant, { ...data, id: uuid(), recipientCount: recipients.length, publishedAt: data.status === 'published' ? now() : undefined, createdAt: now(), updatedAt: now() }); await this.database.db.insert(announcements).values({ id: String(record.id), workspaceId: tenant.workspaceId, title: String(record.title), status: String(record.status ?? 'draft'), priority: String(record.priority ?? 'normal'), payload: record }); if (record.status === 'published') await this.dispatchAnnouncement(tenant, record, recipients); return record; }
  async publishAnnouncement(tenant: Tenant, id: string, actor?: Actor) { assertPermission(actor, 'announcement.publish'); const current = await this.getPayload<JsonRecord>(tenant, announcements, announcements.id, id, 'Announcement'); if (current.status === 'published') return current; const recipients = await this.resolveAudience(tenant, current.audience as JsonRecord, actor); const record = this.withTenant<JsonRecord>(tenant, { ...current, status: 'published', recipientCount: recipients.length, publishedAt: now(), updatedAt: now() }); await this.database.db.update(announcements).set({ status: 'published', payload: record, updatedAt: new Date() }).where(and(eq(announcements.workspaceId, tenant.workspaceId), eq(announcements.id, id))); await this.dispatchAnnouncement(tenant, record, recipients); return record; }
  async archiveAnnouncement(tenant: Tenant, id: string, actor?: Actor) { assertPermission(actor, 'announcement.update'); const current = await this.getPayload<JsonRecord>(tenant, announcements, announcements.id, id, 'Announcement'); const record = this.withTenant<JsonRecord>(tenant, { ...current, status: 'archived', updatedAt: now() }); await this.database.db.update(announcements).set({ status: 'archived', payload: record, updatedAt: new Date() }).where(and(eq(announcements.workspaceId, tenant.workspaceId), eq(announcements.id, id))); return record; }
  async listAnnouncements(tenant: Tenant) { assertPermission(undefined, 'announcement.view'); return (await this.database.db.select().from(announcements).where(eq(announcements.workspaceId, tenant.workspaceId))).map((r) => dto(tenant, r)); }

  async sendCommunication(tenant: Tenant, input: JsonRecord, actor?: Actor) { assertPermission(actor, 'communication.send'); assertText(input.subject, 'Subject'); assertText(input.body, 'Message'); if (!Array.isArray(input.channels) || !input.channels.length) throw new ApiError(400, 'VALIDATION_FAILED', 'At least one delivery channel is required.'); if (input.idempotencyKey) { const found = (await this.database.db.select().from(communicationMessages).where(and(eq(communicationMessages.workspaceId, tenant.workspaceId), eq(communicationMessages.idempotencyKey, String(input.idempotencyKey)))).limit(1))[0]; if (found) return dto(tenant, found); }
    let subject = String(input.subject); let body = String(input.body); if (input.templateId) { const template = await this.getPayload<JsonRecord>(tenant, communicationTemplates, communicationTemplates.id, String(input.templateId), 'Template'); const rendered = this.renderTemplate(template, input.variables as Record<string, string> ?? {}); subject = rendered.subject; body = rendered.content; }
    const recipients = await this.resolveAudience(tenant, input.audience as JsonRecord, actor); if (!recipients.length) throw new ApiError(400, 'VALIDATION_FAILED', 'No valid recipients resolved.'); const created = now(); const status = input.scheduledAt && String(input.scheduledAt) > created ? 'scheduled' : 'sent'; const record = this.withTenant<JsonRecord>(tenant, { id: uuid(), subject, body, senderId: input.senderId, audience: input.audience, channels: input.channels, priority: input.priority ?? 'normal', status, scheduledAt: input.scheduledAt, templateId: input.templateId, idempotencyKey: input.idempotencyKey, recipientCount: recipients.length, createdAt: created, updatedAt: created, sentAt: status === 'sent' ? created : undefined }); await this.database.db.insert(communicationMessages).values({ id: String(record.id), workspaceId: tenant.workspaceId, subject, status, priority: String(record.priority), idempotencyKey: input.idempotencyKey ? String(input.idempotencyKey) : undefined, payload: record }).catch(dbError); if (status === 'sent') for (const recipient of recipients) for (const channel of input.channels as string[]) { if (channel === 'in_app') { const notification = await this.createNotification(tenant, { recipientKind: recipient.kind, recipientId: recipient.id, recipientUserId: recipient.userId, type: 'communication.sent', title: subject, message: body, priority: input.priority ?? 'normal', relatedResourceType: 'communication', relatedResourceId: record.id, actionPath: '/workspace/education/communication/notifications' }); await this.recordDelivery(tenant, { communicationId: record.id, notificationId: notification.id, recipientId: recipient.id, recipientKind: recipient.kind, channel, status: 'sent' }); } else await this.recordDelivery(tenant, { communicationId: record.id, recipientId: recipient.id, recipientKind: recipient.kind, channel, status: 'queued' }); } return record; }
  async listMessages(tenant: Tenant) { assertPermission(undefined, 'communication.view'); return (await this.database.db.select().from(communicationMessages).where(eq(communicationMessages.workspaceId, tenant.workspaceId))).map((r) => dto(tenant, r)); }

  async createNotification(tenant: Tenant, data: JsonRecord) { const record = this.withTenant<JsonRecord>(tenant, { ...data, id: uuid(), isRead: false, createdAt: now() }); await this.database.db.insert(sisNotifications).values({ id: String(record.id), workspaceId: tenant.workspaceId, recipientKind: String(record.recipientKind), recipientId: String(record.recipientId), recipientUserId: typeof record.recipientUserId === 'string' ? record.recipientUserId : undefined, notificationType: String(record.type), isRead: false, payload: record }); return record; }
  async listNotifications(tenant: Tenant, recipient?: { kind?: string; id?: string }) { assertPermission(undefined, 'notification.view'); const rows = await this.database.db.select().from(sisNotifications).where(eq(sisNotifications.workspaceId, tenant.workspaceId)); return rows.map((r) => dto(tenant, r)).filter((n) => !recipient?.kind || (n.recipientKind === recipient.kind && n.recipientId === recipient.id)); }
  async unreadCount(tenant: Tenant, recipient: { kind: string; id: string }) { return (await this.listNotifications(tenant, recipient)).filter((n) => !n.isRead).length; }
  async markRead(tenant: Tenant, id: string, recipient?: { kind?: string; id?: string }) { const current = await this.getPayload<JsonRecord>(tenant, sisNotifications, sisNotifications.id, id, 'Notification'); if (recipient?.kind && (current.recipientKind !== recipient.kind || current.recipientId !== recipient.id)) throw new ApiError(403, 'FORBIDDEN', 'Notification does not belong to this recipient.'); const record = this.withTenant<JsonRecord>(tenant, { ...current, isRead: true, readAt: now() }); await this.database.db.update(sisNotifications).set({ isRead: true, payload: record, updatedAt: new Date() }).where(and(eq(sisNotifications.workspaceId, tenant.workspaceId), eq(sisNotifications.id, id))); return record; }
  async markAllRead(tenant: Tenant, recipient: { kind: string; id: string }) { const rows = await this.database.db.select().from(sisNotifications).where(and(eq(sisNotifications.workspaceId, tenant.workspaceId), eq(sisNotifications.recipientKind, recipient.kind), eq(sisNotifications.recipientId, recipient.id))); let count = 0; for (const row of rows) { const current = dto<JsonRecord>(tenant, row); if (!current.isRead) { count += 1; await this.markRead(tenant, row.id); } } return count; }
  async recordDelivery(tenant: Tenant, data: JsonRecord) { const created = now(); const record = this.withTenant<JsonRecord>(tenant, { ...data, id: uuid(), queuedAt: created, sentAt: data.status === 'sent' ? created : undefined, deliveredAt: data.status === 'delivered' ? created : undefined, failedAt: data.status === 'failed' ? created : undefined, retryCount: 0 }); await this.database.db.insert(communicationDeliveries).values({ id: String(record.id), workspaceId: tenant.workspaceId, communicationId: data.communicationId ? String(data.communicationId) : undefined, announcementId: data.announcementId ? String(data.announcementId) : undefined, notificationId: data.notificationId ? String(data.notificationId) : undefined, recipientId: String(data.recipientId), recipientKind: String(data.recipientKind), channel: String(data.channel), status: String(data.status), payload: record }); return record; }
  async deliveryHistory(tenant: Tenant) { assertPermission(undefined, 'delivery_history.view'); return (await this.database.db.select().from(communicationDeliveries).where(eq(communicationDeliveries.workspaceId, tenant.workspaceId))).map((r) => dto(tenant, r)); }
  async savePreference(tenant: Tenant, data: JsonRecord, actor?: Actor) { assertPermission(actor, 'notification.manage'); const current = data.id ? (await this.database.db.select().from(notificationPreferences).where(and(eq(notificationPreferences.workspaceId, tenant.workspaceId), eq(notificationPreferences.id, String(data.id)))).limit(1))[0] : undefined; const record = this.withTenant<JsonRecord>(tenant, { ...(current ? payloadOf(current.payload) : {}), ...data, id: current?.id ?? uuid(), createdAt: current ? (current.payload as JsonRecord).createdAt : now(), updatedAt: now() }); if (current) await this.database.db.update(notificationPreferences).set({ recipientKind: String(record.recipientKind), recipientId: String(record.recipientId), payload: record, updatedAt: new Date() }).where(and(eq(notificationPreferences.workspaceId, tenant.workspaceId), eq(notificationPreferences.id, current.id))); else await this.database.db.insert(notificationPreferences).values({ id: String(record.id), workspaceId: tenant.workspaceId, recipientKind: String(record.recipientKind), recipientId: String(record.recipientId), payload: record }).catch(dbError); return record; }
  async emitDomainNotification(tenant: Tenant, eventType: string, audience: JsonRecord, payload: JsonRecord) { const recipients = await this.resolveAudience(tenant, audience); const out: JsonRecord[] = []; for (const r of recipients) out.push(await this.createNotification(tenant, { recipientKind: r.kind, recipientId: r.id, recipientUserId: r.userId, type: eventType, title: payload.title, message: payload.message, priority: payload.priority ?? 'normal', relatedResourceType: payload.relatedResourceType, relatedResourceId: payload.relatedResourceId, actionPath: payload.actionPath })); return out; }
  async summary(tenant: Tenant) { const [ann, msg, del, not] = await Promise.all([this.listAnnouncements(tenant), this.listMessages(tenant), this.deliveryHistory(tenant), this.listNotifications(tenant)]); return { publishedAnnouncements: ann.filter((a) => a.status === 'published').length, communicationsSent: msg.filter((m) => m.status === 'sent').length, pendingDeliveries: del.filter((d) => d.status === 'pending' || d.status === 'queued').length, failedDeliveries: del.filter((d) => d.status === 'failed').length, unreadNotifications: not.filter((n) => !n.isRead).length }; }

  private async dispatchAnnouncement(tenant: Tenant, announcement: JsonRecord, recipients: Recipient[]) { for (const recipient of recipients) { const notification = await this.createNotification(tenant, { recipientKind: recipient.kind, recipientId: recipient.id, recipientUserId: recipient.userId, type: 'announcement.published', title: announcement.title, message: announcement.content, priority: announcement.priority, relatedResourceType: 'announcement', relatedResourceId: announcement.id, actionPath: '/workspace/education/communication/announcements' }); await this.recordDelivery(tenant, { announcementId: announcement.id, notificationId: notification.id, recipientId: recipient.id, recipientKind: recipient.kind, channel: 'in_app', status: 'sent' }); } }
  private withTenant<T extends JsonRecord>(tenant: Tenant, data: T): T & { organizationId: string } { return { ...clean(data), organizationId: tenant.organizationId } as unknown as T & { organizationId: string }; }
  private async getPayload<T extends JsonRecord>(tenant: Tenant, table: { payload: unknown; workspaceId: unknown }, idCol: unknown, id: string, label: string): Promise<T> { const row = (await this.database.db.select().from(table as never).where(and(eq(table.workspaceId as never, tenant.workspaceId), eq(idCol as never, id))).limit(1))[0] as { payload: T } | undefined; if (!row) throw new ApiError(404, 'NOT_FOUND', `${label} not found.`); return { ...payloadOf(row.payload), organizationId: tenant.organizationId } as unknown as T; }
}
